const concerts = [
  {
    id: 'a5a9dfae-dc7e-4d35-911e-632096b71617',
    bandName: 'Heideroosjes',
    from: 1660862100000,
    to: 1660865700000,
    place: 'Dance Hall',
    thumbnail: 'https://assets.pukkelpop.be/images/band-detail/814fa8121c9e-heideroosjes.jpg',
    genre: 'Rock, Punk, Alternative',
    biography: 'Na dertig jaar punkrocken zijn Heideroosjes nog altijd niet verwelkt. Het trio uit Nederlands Limburg was al een paar keer gestopt, maar in 2020 verscheen ineens het nieuwe nummer ‘2020, De Tering!’. En daarna kwam plots de ep ‘Infocalyps’. Die klinkt volgens muziekblad Oor “fel, direct en ergens toch aaibaar”. Vintage Heideroosjes, dus. Klaar om ‘tering tyfus takketrut’ mee te brullen?',
  },
  {
    id: '4f4ab5fe-3802-4f43-a098-dc953e0e0213',
    bandName: 'STIKSTOF',
    from: 1660856100000,
    to: 1660859700000,
    place: 'Dance Hall',
    thumbnail: 'https://assets.pukkelpop.be/images/band-detail/410290078538-stikstof.jpg',
    genre: 'Hiphop',
    biography: 'Verwacht niets minder dan pure chaos wanneer de Brusseleirs van STIKSTOF het podium beklimmen. Het collectief met onder andere Zwangere Guy nam op hun laatste twe albums, ‘Familie Boven Alles’ en \'Moeras\', geen enkel blad voor de mond. Eerlijke verhalen van de straat met een loeiharde beat en gruwelijk veel flair. Doe je t-shirt uit en kom lekker mee moshen, ket.',
  },
  {
    id: 'ad0a51d1-63e5-4ada-a9b0-56a6219234a8',
    bandName: 'Coely',
    from: 1660850100000,
    to: 1660853700000,
    place: 'Dance Hall',
    thumbnail: 'https://assets.pukkelpop.be/images/band-detail/2c6adffdf471-coely.jpg',
    genre: 'Hiphop, R&B',
    biography: 'Tien jaar geleden bracht Coely haar debuutsingle ‘Ain’t Chasing Pavements’ uit. Sindsdien opende ze voor Kanye, De La Soul en Kendrick Lamar. En stond ze op Glastonbury. Coely Mbueno hoort ook gewoon thuis tussen de groten der Aarde. De Antwerpse schakelt moeiteloos tussen hiphop om hard op te gaan en soulvolle melodieën die klinken als een warme knuffel op een kille zomeravond.',
  },
  {
    id: 'ad0a51d1-63e5-4ada-a9b0-56a6219234a8',
    bandName: 'Coely',
    from: 1660850100000,
    to: 1660853700000,
    place: 'Dance Hall',
    thumbnail: 'https://assets.pukkelpop.be/images/band-detail/2c6adffdf471-coely.jpg',
    genre: 'Hiphop, R&B',
    biography: 'Tien jaar geleden bracht Coely haar debuutsingle ‘Ain’t Chasing Pavements’ uit. Sindsdien opende ze voor Kanye, De La Soul en Kendrick Lamar. En stond ze op Glastonbury. Coely Mbueno hoort ook gewoon thuis tussen de groten der Aarde. De Antwerpse schakelt moeiteloos tussen hiphop om hard op te gaan en soulvolle melodieën die klinken als een warme knuffel op een kille zomeravond.',
  },
];